# Site settings
title: Pagina Mariano
email: paulotiagocm@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Minha pagina pessoal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ptcmariano.github.io" # the base hostname & protocol for your site
twitter_username: ptcmariano
github_username:  ptcmariano

# Build settings
markdown: kramdown
